# Generated by Django 4.0.5 on 2022-06-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
